import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

test('画布渲染区域中心标签并支持双击切换座位', async () => {
  const source = await readFile(new URL('../src/components/VenueCanvas.vue', import.meta.url), 'utf8')

  assert.match(source, /region-label/)
  assert.match(source, /markerMode/)
  assert.match(source, /@dblclick\.stop="onMarkerSeatToggle\(element\)"/)
  assert.match(source, /marker-seat-toggle/)
  assert.match(source, /marker-rect-select/)
  assert.match(source, /markerSelectionRect/)
  assert.match(source, /startMarkerRectSelection/)
  assert.match(source, /selectReservedRegionFromSeat/)
  assert.match(source, /activeMarkerId/)
  assert.match(source, /reservedItem\.id !== props\.activeMarkerId/)
  assert.match(source, /pointer-events:\s*none/)
  assert.match(source, /\.region-label\s*\{[\s\S]*background:\s*transparent;/)
  assert.match(source, /\.region-label\s*\{[\s\S]*border:\s*0;/)
  assert.match(source, /\.region-label\s*\{[\s\S]*text-shadow:/)
  assert.doesNotMatch(source, /\.region-label\s*\{[\s\S]*border-radius:\s*999px/)
  assert.doesNotMatch(source, /\.region-label:hover/)
  assert.doesNotMatch(source, /@click\.stop="emit\('marker-select', anchor\.source\)"/)
})

test('区域面板沿用人员面板的简洁侧栏样式且不放底部保存', async () => {
  const source = await readFile(new URL('../src/components/RegionMarkerPanel.vue', import.meta.url), 'utf8')

  assert.match(source, /区域名称/)
  assert.match(source, /已选座位/)
  assert.match(source, /已有区域/)
  assert.match(source, /删除区域/)
  assert.match(source, /ColorPickerPopover/)
  assert.match(source, /textColorForBackground/)
  assert.match(source, /usedMarkerColors/)
  assert.match(source, /:unavailable-colors="usedMarkerColors"/)
  assert.match(source, /class="panel-heading"/)
  assert.match(source, /class="panel-tools marker-list-section"/)
  assert.match(source, /SidePanelEmptyState/)
  assert.match(source, /class="marker-detail-section"/)
  assert.match(source, /class="empty-marker-list"/)
  assert.match(source, /\.region-marker-panel\s*\{[\s\S]*gap:\s*12px;[\s\S]*padding:\s*16px;[\s\S]*overflow:\s*hidden;/)
  assert.match(source, /\.empty-marker-list\s*\{[\s\S]*place-items:\s*center;/)
  assert.doesNotMatch(source, />\s*保存区域\s*</)
  assert.doesNotMatch(source, />\s*重置\s*</)
  assert.doesNotMatch(source, /新建区域/)
  assert.doesNotMatch(source, /区域标记/)
  assert.doesNotMatch(source, /选择方式/)
  assert.doesNotMatch(source, /el-segmented/)
  assert.doesNotMatch(source, /添加座位/)
  assert.doesNotMatch(source, /移除座位/)
})

test('工作台区域模式支持框选创建并保存 RESERVED 区域', async () => {
  const source = await readFile(new URL('../src/views/WorkbenchView.vue', import.meta.url), 'utf8')

  assert.match(source, /RegionCreateDialog/)
  assert.match(source, /openRegionCreateDialog/)
  assert.match(source, /createReservedAreaFromDialog/)
  assert.match(source, /mergeReservedAreaFromDialog/)
  assert.match(source, /saveReservedAreas/)
  assert.match(source, /RegionMarkerPanel/)
  assert.match(source, /markerAreaDrafts/)
  assert.match(source, /canvasWorkspace/)
  assert.match(source, /markerDirty/)
  assert.match(source, /recordMarkerHistory/)
  assert.match(source, /restoreMarkerHistorySnapshot/)
  assert.match(source, /toReservedAreaPayload/)
  assert.match(source, /markerAreaDrafts\.value\.map\(toReservedAreaPayload\)/)
  assert.match(source, /markerSelection/)
  assert.match(source, /selectReservedMarker\(blockingItem\)/)
  assert.match(source, /deleteReservedMarker\(true,\s*false\)/)
  assert.match(source, /:active-marker-id="markerDraft\.id"/)
  assert.match(source, /validateMarkerUniqueness/)
  assert.match(source, /区域名称已存在/)
  assert.match(source, /区域颜色已被其他区域使用/)
  assert.doesNotMatch(source, /区域标记/)
  assert.doesNotMatch(source, /markerSeatMode/)
})

test('区域创建弹窗复用本地自定义颜色能力', async () => {
  const source = await readFile(new URL('../src/components/RegionCreateDialog.vue', import.meta.url), 'utf8')

  assert.match(source, /创建区域/)
  assert.match(source, /合并到已有区域/)
  assert.match(source, /mergeTargetId/)
  assert.match(source, /markers/)
  assert.match(source, /mode/)
  assert.match(source, /emit\('merge'/)
  assert.match(source, /区域名称/)
  assert.match(source, /ColorPickerPopover/)
  assert.match(source, /textColorForBackground/)
  assert.match(source, /isDuplicateLabel/)
  assert.match(source, /isDuplicateColor/)
  assert.match(source, /区域名称已存在/)
  assert.match(source, /区域颜色已被其他区域使用/)
})
