create table t_venue_templates (
    id varchar(36) primary key,
    name varchar(120) not null,
    description varchar(500),
    grid_rows integer not null,
    grid_columns integer not null,
    cell_size integer not null,
    version_no integer not null,
    preset boolean not null,
    front_direction varchar(20) not null,
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null
);

create table t_venue_elements (
    id varchar(36) primary key,
    venue_template_id varchar(36) not null,
    element_type varchar(30) not null,
    code varchar(80),
    label varchar(120),
    grid_row integer not null,
    grid_column integer not null,
    row_span integer not null,
    column_span integer not null,
    rotation integer not null,
    capacity integer not null,
    assignable boolean not null,
    walkable boolean not null,
    group_code varchar(80),
    group_label varchar(80),
    sequence_no integer,
    background_color varchar(20),
    border_color varchar(20),
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null,
    constraint fk_t_venue_element_template foreign key (venue_template_id) references t_venue_templates(id)
);

create table t_meetings (
    id varchar(36) primary key,
    name varchar(160) not null,
    status varchar(30) not null,
    venue_template_id varchar(36),
    layout_name varchar(120) not null,
    grid_rows integer not null,
    grid_columns integer not null,
    cell_size integer not null,
    layout_version integer not null,
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null,
    constraint fk_t_meeting_template foreign key (venue_template_id) references t_venue_templates(id)
);

create table t_meeting_elements (
    id varchar(36) primary key,
    meeting_id varchar(36) not null,
    source_element_id varchar(36),
    element_type varchar(30) not null,
    code varchar(80),
    label varchar(120),
    grid_row integer not null,
    grid_column integer not null,
    row_span integer not null,
    column_span integer not null,
    rotation integer not null,
    capacity integer not null,
    assignable boolean not null,
    walkable boolean not null,
    group_code varchar(80),
    group_label varchar(80),
    sequence_no integer,
    background_color varchar(20),
    border_color varchar(20),
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null,
    constraint fk_t_meeting_element_meeting foreign key (meeting_id) references t_meetings(id)
);

create table t_participants (
    id varchar(36) primary key,
    meeting_id varchar(36) not null,
    employee_no varchar(9) not null,
    name varchar(80) not null,
    level_value integer,
    department varchar(160),
    participant_type varchar(80),
    tags varchar(500),
    custom_attributes_json text,
    locked boolean not null,
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null,
    constraint fk_t_participant_meeting foreign key (meeting_id) references t_meetings(id),
    constraint uk_t_participant_employee unique (meeting_id, employee_no)
);

create table t_award_records (
    id varchar(36) primary key,
    participant_id varchar(36) not null,
    batch_order integer not null,
    batch_name varchar(80) not null,
    award_name varchar(200) not null,
    award_level varchar(80),
    project_name varchar(240),
    team_size integer,
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null,
    constraint fk_t_award_participant foreign key (participant_id) references t_participants(id)
);

create table t_seating_plans (
    id varchar(36) primary key,
    meeting_id varchar(36) not null,
    name varchar(120) not null,
    status varchar(30) not null,
    current_version_no integer not null,
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null,
    constraint fk_t_plan_meeting foreign key (meeting_id) references t_meetings(id)
);

create table t_plan_items (
    id varchar(36) primary key,
    plan_id varchar(36) not null,
    item_type varchar(30) not null,
    participant_id varchar(36),
    label varchar(120),
    locked boolean not null,
    background_color varchar(20),
    text_color varchar(20),
    bold boolean not null,
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null,
    constraint fk_t_item_plan foreign key (plan_id) references t_seating_plans(id),
    constraint fk_t_item_participant foreign key (participant_id) references t_participants(id)
);

create table t_plan_item_targets (
    id varchar(36) primary key,
    plan_item_id varchar(36) not null,
    meeting_element_id varchar(36) not null,
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null,
    constraint fk_t_target_item foreign key (plan_item_id) references t_plan_items(id),
    constraint fk_t_target_element foreign key (meeting_element_id) references t_meeting_elements(id),
    constraint uk_t_target_element unique (meeting_element_id)
);

create table t_plan_versions (
    id varchar(36) primary key,
    plan_id varchar(36) not null,
    version_no integer not null,
    version_name varchar(120) not null,
    change_note varchar(500),
    automatic boolean not null,
    snapshot_json text not null,
    assigned_count integer not null,
    unassigned_count integer not null,
    created_by_id varchar(64) not null,
    created_by_name varchar(80) not null,
    created_at timestamp with time zone not null,
    updated_by_id varchar(64) not null,
    updated_by_name varchar(80) not null,
    updated_at timestamp with time zone not null,
    deleted boolean not null,
    row_version bigint not null,
    constraint fk_t_version_plan foreign key (plan_id) references t_seating_plans(id),
    constraint uk_t_plan_version unique (plan_id, version_no)
);
